language: ruby
rvm:
- 2.4.1
dist: trusty
sudo: required
branches:
  only:
  - master
cache:
  bundler: true
  yarn: true
  directories:
  - node_modules
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
notifications:
  email:
    on_success: never
    on_failure: change
  pushover:
    api_key:
      secure: pID1ItdNX6R8d0X/8E+AoHTEUCOIzyL35G47j1LhS8UkRNYhJRTK3iQXelbrDfCtpfb06qhAkxcZx7vXgflDI6cOURMVv6Egg3My+WLhSI+SyFli0QBWZKyDYD1/88ERzIlyZbFYiNde7lNROOXdHPD4khCgo3/3JWXOn6Y47S5lLu1e8cWe6T6o6rN7duRXCDY0XGSfslHt5iMf+b/1kL1cZeZlP8JyvSXSxinfeY/GVGFQQnwoKPHA/eWcXPz/ek7mOgX1++c+Vbkwf2TjAhv5IzzmLEqE9RzT1R7L0N5dl/VmauWETYc0GU6Y/L3dNNZDjJRP84+A1xKVy95cGUh/pr0Auabj5CtmLzAomSw/YsQeYwmMNW1gMe4P/USQOsnSogyVbeJs1yXjmLWtsddUaLDT64DLh1/KQzHIOjb3zglPBXYUeiXdJg2nEazFae8rVFk1BcvQ1gwC9s1+9PQG5nhmilbs4LwJxHzko5j0R92R1fbBczj5i75Gy8+XLS4/PCdznLztVRMxMuEGkrtWzsCuGLB2GXDczRls8f9ke3KoECdqgbm7LWxWCIwlG1XdiJk4JivWT2njTbNfYODJXJKq9KShe4BeQ2rrasWQv2d/ko0Im0CVP7VqRtQgxIQNe6Ut0di7xeGvyhAx9789VKbgEF1+MyVMZ0GNu7o=
    users:
      secure: NmnPQlide6W/7DbUzIrOlPZNfvIZ/zBgJC3GXHKZzr8XflVYw0OG0P4WEovNcrZ9Y8EKC+1XobK6Eq2WjLVDLpseP50Dnu0JcN2uUkXNqQnzmjXWoGT8ymgBYkijLWGEFk2+j8zTq1TJvrQSkes9JUOPn8PXM8jev9VvSQbvga1S6xW106YyC+HcDeaYvXGCh65MeF9JH8URHoQpyf3xp1JeRGuiDUHoS+fbbJUUlqf04xeTlxOzvhpDcnvpU8lwQKfYfKoZPcNCjY9plEYOS9oQKTeClQzJzUs2N8N2bUlSg94eCJ3hiAz7yHG5h+E/GF24/Sz0bKRszlAhYzupv4uaBAfW2Dd+YakOGORb2nePhNXJW9Y/BKc7JXRnWoF6DkMpMoarakegctR/H3uSCRGMAv5hLAZx64sn6y4mDfZyyUQbZao/9B669vzoS4ioRsXZYn7KL09E0RxMMrZSvwnkY8UkpNPROiv7f9664iAV/L0Hlq3aZD4HcdNfMQauyGayP649q5R+dlvdFXcP+PU1tjYHAPmWQ8Lo8KfvgJ0W6SM5Ex+wptssOmP+ma+vRj6NKzN8VkeExW4AwgRtSW+ckJlS0HMdt2kBp6RslcrPDwzK8y6lRrhSlEnW4+I5jgODMJ5q0o8mwuyYjw3k6b0Dt5QD0Z25gusiUKeZKBM=
before_install:
- nvm install 9.5
- gem update --system
- gem install bundler
install:
- npm install -g gulp-cli
- npm install
- bundle install
script: travis_retry gulp build --prod
deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: 1/gXv4_MWz4DUHzo05irUjoVBBHCqy5gbsXGrDj2adyejlgDSpM04k0Ag8oIEGdlx7
  project: statewideroofing-86d6c
after_deploy:
- gulp submit
