branches:
  only:
  - "/.*/"
language: ruby
rvm:
- 2.5.3
dist: xenial
node_js: 12.13.1
cache:
  bundler: true
  directories:
  - node_modules
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  secure: "RsinwBY28TO1B0UVyntGR4AKv4flKvN/LXpQ3dYdK/Py1EZclzvU4eH1X9veObznpQC9e0UChExq6PkDh3B1P3rHSIymC18Kj6cesFXfBuwXGG+9nYJhePY6ysEc0TOoSdtAOCiWhEU4T9nHp7uF4YUEKOzamqAMkfDmizPRNAGh3fWAXPqPW4xz5vbaYaJb2fzXRZ0iMqBx0xttY4vQG03vPsxqrlvMDVfgAsq04ac130FZblaDvmA+GpRKmzcDREWNb0hioyJrLajCqtBFMfd4FV0hmvF/Tz65wvm/dM1+NIfOBMXMdk0XRVaAQtooCqZg/s/aQnm7FvbSGfpjUo16lu0+kASkal5n32xzBzQ1UPpP5cvwRZE+047sJo08Kg833EdlEZOlFe0tL2l4JK237msF+Me9ats4iaoFRSy/rjxWGYJ/0+Ck1XmsM7kFV0edRNh+Hr+h8nSivkUrkdLGulGXV7Xv5W4j8MCfz5YrIRwOT2mIFcKU2kuMglIKEKEbSoZrAZJ2oO7wxey7JEvn5zMtqkn+OjZW6kjnoisJtv35q1HEq/U0cgAHrkjyEEh9CsXy/NHhEI0NiDMfhYUbAVEnEZEfWnxUoONzny6K2+2PrFSFQmCfHNABl8RmG0MVOB3m8198IMCMUkFrvXDDPqp1z9vEdV1sa7RbLGs="
notifications:
  email:
    on_success: change
    on_failure: change
  pushover:
    api_key:
      secure: pID1ItdNX6R8d0X/8E+AoHTEUCOIzyL35G47j1LhS8UkRNYhJRTK3iQXelbrDfCtpfb06qhAkxcZx7vXgflDI6cOURMVv6Egg3My+WLhSI+SyFli0QBWZKyDYD1/88ERzIlyZbFYiNde7lNROOXdHPD4khCgo3/3JWXOn6Y47S5lLu1e8cWe6T6o6rN7duRXCDY0XGSfslHt5iMf+b/1kL1cZeZlP8JyvSXSxinfeY/GVGFQQnwoKPHA/eWcXPz/ek7mOgX1++c+Vbkwf2TjAhv5IzzmLEqE9RzT1R7L0N5dl/VmauWETYc0GU6Y/L3dNNZDjJRP84+A1xKVy95cGUh/pr0Auabj5CtmLzAomSw/YsQeYwmMNW1gMe4P/USQOsnSogyVbeJs1yXjmLWtsddUaLDT64DLh1/KQzHIOjb3zglPBXYUeiXdJg2nEazFae8rVFk1BcvQ1gwC9s1+9PQG5nhmilbs4LwJxHzko5j0R92R1fbBczj5i75Gy8+XLS4/PCdznLztVRMxMuEGkrtWzsCuGLB2GXDczRls8f9ke3KoECdqgbm7LWxWCIwlG1XdiJk4JivWT2njTbNfYODJXJKq9KShe4BeQ2rrasWQv2d/ko0Im0CVP7VqRtQgxIQNe6Ut0di7xeGvyhAx9789VKbgEF1+MyVMZ0GNu7o=
    users:
      secure: NmnPQlide6W/7DbUzIrOlPZNfvIZ/zBgJC3GXHKZzr8XflVYw0OG0P4WEovNcrZ9Y8EKC+1XobK6Eq2WjLVDLpseP50Dnu0JcN2uUkXNqQnzmjXWoGT8ymgBYkijLWGEFk2+j8zTq1TJvrQSkes9JUOPn8PXM8jev9VvSQbvga1S6xW106YyC+HcDeaYvXGCh65MeF9JH8URHoQpyf3xp1JeRGuiDUHoS+fbbJUUlqf04xeTlxOzvhpDcnvpU8lwQKfYfKoZPcNCjY9plEYOS9oQKTeClQzJzUs2N8N2bUlSg94eCJ3hiAz7yHG5h+E/GF24/Sz0bKRszlAhYzupv4uaBAfW2Dd+YakOGORb2nePhNXJW9Y/BKc7JXRnWoF6DkMpMoarakegctR/H3uSCRGMAv5hLAZx64sn6y4mDfZyyUQbZao/9B669vzoS4ioRsXZYn7KL09E0RxMMrZSvwnkY8UkpNPROiv7f9664iAV/L0Hlq3aZD4HcdNfMQauyGayP649q5R+dlvdFXcP+PU1tjYHAPmWQ8Lo8KfvgJ0W6SM5Ex+wptssOmP+ma+vRj6NKzN8VkeExW4AwgRtSW+ckJlS0HMdt2kBp6RslcrPDwzK8y6lRrhSlEnW4+I5jgODMJ5q0o8mwuyYjw3k6b0Dt5QD0Z25gusiUKeZKBM=
before_install:
- nvm install 12.13.1
- nvm use 12.13.1
- gem update --system
- gem update bundler
- gem install bundler
install:
- npm install -g firebase-tools
- npm install -g gulp-cli
- npm install -g snyk
- firebase use "$FIREBASE_PROJECT" --token "$FIREBASE_TOKEN"
- npm install
- bundle install
script:
- travis_retry gulp build --prod
after_success:
- firebase --non-interactive deploy --token "$FIREBASE_TOKEN"
- gulp submit
