# ----
# Site
source                   : ".tmp/src"
destination              : ".tmp/dist"

title: "Statewide Roofing"
url: "https://www.statewideroofing.net.au"
baseurl: ""
environment: "production"
repository: "https://github.com/itsolver/statewideroofing.net.au"
timezone: "Australia/Brisbane"
google_analytics_key: "UA-114652588-1"
disqus_shortname: ""
icon_ready: true
twitter:
  username: ""
future: false # Publish on schedule future dated posts https://stackoverflow.com/a/5013966
# ----
# Business profile
short-name: "SWR"
QBCC: "111 8722"
ABN: "80 169 475 912"
email: "info@statewideroofing.net.au"
# Include area code
phone: "1300 784 231"
fax: "1300 784 235"
# Update country code for tel: links
phone-country-code: "61"
mailing-address: P.O. Box 7456, Loganholme QLD 4129
operating-days: Monday - Friday
operating-hours: 9am - 5pm
google-maps-embed: https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3619441.276589764!2d150.9517851482728!3d-27.636573679307585!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x6b9141eff73f7ef5%3A0xfa484253a27fbc0c!2sStatewide+Roofing+(Queensland)+Pty+LTD!5e0!3m2!1sen!2sau!4v1519642183049

# Let search engines discover this site quicker
google_site_verification : ""
bing_site_verification   : ""
alexa_site_verification  : ""
yandex_site_verification : ""

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: "/assets/images/statewide-roofing-logo.png"
description: "The metal roofing specialists."
facebook:
  publisher: ""
  admins: ""
author:
  picture: ""
  twitter: ""
social:
  name: ""
  links:

# -----
# Build

permalink: "pretty"
defaults:
  - scope:
      path: ""
    values:
      header_class: "plain"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

collections:
  case_studies:
    output: false
    permalink: /case-studies/:name/

exclude:
- .asset-cache
- .bundle
- .jekyll-assets-cache
- .sass-cache
- "*.sublime-project"
- "*.sublime-workspace"
- Capfile
- config
- Gemfile
- Gemfile.lock
- Gruntfile.js
- gulpfile.js
- log
- node_modules
- package.json
- Rakefile
- README
- tmp
- vendor/bundle/
- vendor/cache/
- vendor/gems/
- vendor/ruby/

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed

# -----------
# CloudCannon

social_icons:
  - Facebook
  - Google-Plus
  - Instagram
  - LinkedIn
  - Pinterest
  - Tumblr
  - Twitter
  - YouTube
  - RSS
